name: Update version.nix
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # Every 6 hrs Feb-Dec Fri-Sun
    - cron: '0 0/6 * 2-11 5,6,0'
    # Once a week Fridays Dec-Jan
    - cron: '0 0 * 1,12 FRI'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update version.nix
        run: ./update.sh
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update version.nix
          commit-message: Update version.nix
          branch: actions/update_version
          labels: |                  # Labels to be set on the PR
            updates
            automated
